apiVersion: v1
kind: Pod

metadata:
  name: attacker-pod
  namespace: security

spec:
  containers:
    - name: attacker
      image: curlimages/curl
      command: ["/bin/sh"]
      args: ["-c", "sleep 3600"]

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault

  restartPolicy: Never