apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
  namespace: security

spec:
  serviceAccountName: irsa-sa

  containers:
    - name: aws-cli
      image: amazon/aws-cli
      command: ["/bin/sh"]
      args: ["-c", "sleep 3600"]

      env:
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /tmp/.aws/credentials
        - name: AWS_CONFIG_FILE
          value: /tmp/.aws/config
        - name: HOME
          value: /tmp

      volumeMounts:
        - name: aws-temp
          mountPath: /tmp/.aws

      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault

  volumes:
    - name: aws-temp
      emptyDir: {}

  restartPolicy: Never