apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: logging
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::584673484425:role/fluentbit-irsa-role

    ##Gives identity to pods
    ##Connects Kubernetes → AWS IAM (IRSA)