apiVersion: v1
kind: Service
metadata:
    name: eks-enterprise-service
    spec:
       type: NodePort
       selector:
         app: eks-enterprise
       ports:
       - name: http
         protocol: TCP
         port: 3000
         targetPort: 3000
         nodePort: 30007
