apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: secure-nodepool
spec:
  template:
    spec:
      nodeClassRef:
        name: secure-nodeclass

      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]

        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["t3.medium","t3.large"]

  limits:
    cpu: 100

  disruption:
    consolidationPolicy: WhenUnderutilized
