apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: image-verification-policy

spec:
  validationFailureAction: Enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail

  rules:
    - name: verify-signed-images

      match:
        any:
          - resources:
              kinds:
                - Pod
                - Deployment
                - StatefulSet
                - DaemonSet
                - Job
                - CronJob

      verifyImages:
        - imageReferences:
            - "*.dkr.ecr.ap-south-1.amazonaws.com/*"

          mutateDigest: true
          required: true
          verifyDigest: true

          attestors:
            - count: 1
              entries:
                - keys:
                    publicKeys: |-
                      -----BEGIN PUBLIC KEY-----
                      REPLACE_WITH_YOUR_COSIGN_PUBLIC_KEY
                      -----END PUBLIC KEY-----

          annotations:
            cosign.sigstore.dev/imageRef: "{{ image.reference }}"
